### PR TITLE
Support mixed text code in spm_encode

### PR DESCRIPTION
**Pull request by yiyangh-ps**

### CODE REVIEW

**Comment by rbehjati** [comment]
@yiyangh-ps What is the status of this PR? Can I use the new functionality in the encoder?

**Comment by yiyangh-ps** [comment]
Yes it should be functional.

**Comment by rbehjati** [comment]
Thanks @yiyangh-ps. 

Not sure if you plan to merge this PR, but the code is not very readable in its current form, and will be difficult to maintain. I suggest moving the poolside-specific logic to a separate function, and perhaps to a separate file, and make it testable too.

**Comment by yiyangh-ps** [comment]
I am closing this PR because I merged this into #4

**Pull request closed without merging**
